[package]
name = "dungeon-dash"
version = "0.1.0"
edition = "2021"

[dependencies]
turbo = { version = "1.6.0-alpha.14", package = "turbo-genesis-sdk" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
crate-type = ["cdylib"]
