[package]
name = "dungeon-dash"
version = "0.1.0"
edition = "2021"

[dependencies]
# turbo = { version = "1.6.0-alpha.7", package = "turbo-genesis-sdk" }
turbo = { version = "1.6.0-alpha.9", package = "turbo-genesis-sdk" }

[lib]
crate-type = ["cdylib"]
